### PR TITLE
Updates in preparation for CRAN submission

### PR DESCRIPTION
**Pull request by bmbroom**
Various updates in preparation for CRAN submission

### CODE REVIEW

**Comment by marohrdanz** [comment]
Three small things:

1. CRAN says a single person must be specified as a 'Maintainer'. (https://cran.r-project.org/web/packages/policies.html)

2. The CRAN pull request for NGCHM-R bumps the version number by 0.0.1. Can we do the same here?

3. I think we can simply remove the GBM demo data. It seems we planed to do it:

     - In pull request #2, we said that after the NGCHM-R package was updated to use the BRCA data, we could remove the GBM demo data from here.
     - We updated the NGCHM-R package to use the BRCA data in https://github.com/MD-Anderson-Bioinformatics/NGCHM-R/pull/24

   This removal will reduce size of the tar.gz file from 12MB to 2.6MB

**Comment by bmbroom** [comment]
1. Adding role "cre" to a person in the Author@R field is equivalent to specifying a maintainer.
     * We might want to change the maintainer to me for submission to CRAN, so that all three NGCHM packages are submitted by the same person.
 2. Yes.
 3. I would like to try and keep the TCGA.GBM.EXPR data for two reasons:
     * Existing tutorials use it and some are hard to impossible to change (YouTube videos). Moving it to a split out data package is much more palatable than just disappearing it.
     * It provides an interesting contrast to the TCGA.GBM.ExpressionData.  I think we could do a vignette for a multi-layer NGCHM that allows users to compare and contrast the RNASeq and microarray data.

    Since we plan to never update the data, there's a possibility CRAN will permit it.  If not, so be it.  But I would rather ask than just assume we can't do it.

**Comment by marohrdanz** [comment]
I'd forgotten about the YouTube video.

Should we mention in the DESCRIPTION the GBM data has the problem that made us create https://github.com/MD-Anderson-Bioinformatics/NGCHMDemoData/pull/2?

The zzz.R file loads the BRCA data, but not the GBM data. Should we also load the GBM data there?

**Review by marohrdanz — APPROVED** [review]
These changes seem reasonable after discussion.

**Review by jmelott — APPROVED** [review]

**Pull request merged**
